export const musicData = {
  currentPlaylistIndex: 0,
  playlists: [
    {
      artistId: "4Zg0XlpXyAa4TJVSzVNfZF",
      playlistName: "FASSounds Mix",
      tracks: {
        1: "public/assets/music/1 - FASSounds/1 - Lofi Study.mp3",
        2: "public/assets/music/1 - FASSounds/2 - Good Night.mp3",
        3: "public/assets/music/1 - FASSounds/3 - Jazz Café.mp3",
        4: "public/assets/music/1 - FASSounds/4 - Coding Night.mp3",
        5: "public/assets/music/1 - FASSounds/5 - Street Food.mp3",
        6: "public/assets/music/1 - FASSounds/6 - The Fighter.mp3",
        7: "public/assets/music/1 - FASSounds/7 - Hard ADM Phonk.mp3",
        8: "public/assets/music/1 - FASSounds/8 - Best Time.mp3",
        9: "public/assets/music/1 - FASSounds/9 - Staycation.mp3",
        10: "public/assets/music/1 - FASSounds/10 - Chill Night.mp3",
        11: "public/assets/music/1 - FASSounds/11 - Lofi Vintage.mp3",
        12: "public/assets/music/1 - FASSounds/12 - Cooking Beats.mp3",
        13: "public/assets/music/1 - FASSounds/13 - Happy Halloween.mp3",
      },
    },
    {
      artistId: "73aKnLT4O8G2pBEfdlQzrE",
      playlistName: "Purrple Cat Compilation",
      songs: {
        1: "public/assets/music/2 - Purrple Cat/1 - Storm Clouds.mp3",
        2: "public/assets/music/2 - Purrple Cat/2 - Journey's End.mp3",
        3: "public/assets/music/2 - Purrple Cat/3 - Signs of Life.mp3",
        4: "public/assets/music/2 - Purrple Cat/4 - Sugar Coat.mp3",
        5: "public/assets/music/2 - Purrple Cat/5 - Cats Cradle.mp3",
        6: "public/assets/music/2 - Purrple Cat/6 - Wanted.mp3",
        7: "public/assets/music/2 - Purrple Cat/7 - Wondering.mp3",
        8: "public/assets/music/2 - Purrple Cat/8 - Sleepless.mp3",
        9: "public/assets/music/2 - Purrple Cat/9 - Crescent Moon.mp3",
        10: "public/assets/music/2 - Purrple Cat/10 - Bedhead.mp3",
        11: "public/assets/music/2 - Purrple Cat/11 - Moonlit Walk.mp3",
        12: "public/assets/music/2 - Purrple Cat/12 - Dreams come true.mp3",
      },
    },
    {
      artistId: "1mIePRs1ixMW0gTaTSbX2p",
      playlistName: "Ghostrifter Official!",
      songs: {
        1: "public/assets/music/3 - Ghostrifter Official/1 - Morning Routine [Lofi Study Music].mp3",
        2: "public/assets/music/3 - Ghostrifter Official/2 - Purple Dream.mp3",
        3: "public/assets/music/3 - Ghostrifter Official/3 - Downtown Glow (Ghostrifter Official & Devyzed).mp3",
        4: "public/assets/music/3 - Ghostrifter Official/4 - On My Way [Lofi Study Music].mp3",
        5: "public/assets/music/3 - Ghostrifter Official/5 - Still Awake [Lofi Study Music].mp3",
        6: "public/assets/music/3 - Ghostrifter Official/6 - Midnight Stroll [Lofi Study Music].mp3",
        7: "public/assets/music/3 - Ghostrifter Official/7 - City Lights.mp3",
        8: "public/assets/music/3 - Ghostrifter Official/8 - Celestia.mp3",
        9: "public/assets/music/3 - Ghostrifter Official/9 - Hope [Emotional Soundtrack].mp3",
      },
    },
    {
      artistId: "4SYTMJWp1zw7CeOqO6Nk2K",
      playlistName: "CMT8 OCT2023",
      songs: {
        1: "public/assets/music/4 - CMT8/1 - Sleepy cat.mp3",
        2: "public/assets/music/4 - CMT8/2 - Empty mind.mp3",
        3: "public/assets/music/4 - CMT8/3 - Go home.mp3",
        4: "public/assets/music/4 - CMT8/4 - Untitled.mp3",
        5: "public/assets/music/4 - CMT8/5 - Dripping.mp3",
        6: "public/assets/music/4 - CMT8/6 - Night Coffeeshop.mp3",
        7: "public/assets/music/4 - CMT8/7 - Wait.mp3",
        8: "public/assets/music/4 - CMT8/8 - In the room (when the rain pouring).mp3",
      },
    },
    {
      artistId: "5VWxPzSlM3bEky01nXffoN",
      playlistName: "Oleg SoulProdMusic",
      songs: {
        1: "public/assets/music/5 - SoulProdMusic/1 - Aesthetics.mp3",
        2: "public/assets/music/5 - SoulProdMusic/2 - Oktober [Lofi Jazzy beat].mp3",
        3: "public/assets/music/5 - SoulProdMusic/3 - Old clock [chill lofi beats].mp3",
        4: "public/assets/music/5 - SoulProdMusic/4 - Autumn.mp3",
        5: "public/assets/music/5 - SoulProdMusic/5 - Mysterious forest [creepy lofi halloween].mp3",
        6: "public/assets/music/5 - SoulProdMusic/6 - Sweet Breeze.mp3",
        7: "public/assets/music/5 - SoulProdMusic/7 - The Floop.mp3",
        8: "public/assets/music/5 - SoulProdMusic/8 - Move on.mp3",
      },
    },
  ],
};
